using System;
using static BattleRuntimeDefinitions;
static class Program {
 static int assertions;
 static void Eq<T>(T actual,T expected,string label) { assertions++; if(!Equals(actual,expected))throw new Exception($"{label}: 기대 {expected}, 실제 {actual}"); }
 static void Main() {
  var b=new TrainingBattleManager(); var p=b.playerData;
  p.AddBuff(GrowingFeatherBuffId,2);b.enhance=true;b.duplicate=true;b.playerService.OnPlayerTurnStart();
  Eq(b.handManager.cards.Count,4,"깃털 생성과 복제");Eq(b.handManager.cards[0].cardId,203081,"깃털 강화");Eq(p.GetBuffStack(FeatherBuffId),0,"자신에게 깃털 미부여");
  b=new();p=b.playerData;p.AddBuff(GlacierShapeOnHitBuffId,2);b.playerService.ResolveDeferredTurnStartEffects();
  Eq(b.handManager.cards.Count,2,"산산조각 생성");Eq(p.GetBuffStack(GlacierShapeOnHitBuffId),0,"산산조각 소모");b.playerService.ResolveDeferredTurnStartEffects();Eq(b.handManager.cards.Count,2,"산산조각 재발동 방지");
  b=new();p=b.playerData;var power=new Card{power=true,cardId=123,cost=2};var ordinary=new Card();p.AddBuff(RepeatNextPowerCardBuffId,3);
  Eq(b.playerService.ConsumeRepeatCount(ordinary,false),0,"일반 카드 파워 반복 제외");Eq(p.GetBuffStack(RepeatNextPowerCardBuffId),3,"일반 카드는 생성 중첩 유지");
  Eq(b.playerService.ConsumeRepeatCount(power,true),0,"반복 효과는 복사 미발동");Eq(b.handManager.cards.Count,0,"반복 효과 복사 없음");
  Eq(b.playerService.ConsumeRepeatCount(power,false),0,"파워 효과 자동 반복 없음");Eq(b.handManager.cards.Count,3,"다음 파워 카드 세 장 생성");Eq(p.GetBuffStack(RepeatNextPowerCardBuffId),0,"생성 후 모든 중첩 소모");
  foreach(var copy in b.handManager.cards){Eq(copy.cardId,123,"생성 카드 번호");Eq(copy.cost,2,"생성 카드 비용");Eq(copy.power,true,"생성 카드 파워 키워드");Eq(ReferenceEquals(copy,power),false,"독립 카드 복사");}
  p.AddBuff(RepeatNextPowerCardBuffId,2);b.playerService.OnCardPlayed(power,null,false);Eq(p.GetBuffStack(RepeatNextPowerCardBuffId),2,"사용한 카드가 새로 준 중첩 유지");Eq(b.handManager.cards.Count,3,"사용 완료 콜백에서 중복 생성 없음");
  p.AddBuff(RepeatNextCardBuffId,10);p.AddBuff(RepeatNextCardBuffId,3);Eq(p.GetBuffStack(RepeatNextCardBuffId),1,"재사용 추가로 중첩되지 않음");p.SetBuffStack(RepeatNextCardBuffId,7);Eq(p.GetBuffStack(RepeatNextCardBuffId),1,"재사용 직접 설정도 최대 하나");Eq(b.playerService.ConsumeRepeatCount(ordinary,false),1,"재사용 한 번");Eq(p.GetBuffStack(RepeatNextCardBuffId),0,"재사용 발동 후 제거");
  b=new();p=b.playerData;b.playerService.OnPlayerTurnStart();p.AddBuff(HighCostRepeatBuffId,1);var costly=new Card{cost=2};
  Eq(b.playerService.ConsumeRepeatCount(costly,false),1,"턴 도중 풀하우스 획득");Eq(b.playerService.ConsumeRepeatCount(costly,false),0,"풀하우스 턴당 한 번");p.RemoveBuffStack(HighCostRepeatBuffId);b.playerService.OnPlayerTurnStart();p.AddBuff(HighCostRepeatBuffId,1);Eq(b.playerService.ConsumeRepeatCount(costly,false),1,"풀하우스 비활성 턴에도 초기화");
  b=new();p=b.playerData;p.AddBuff(LastStandBuffId,1);p.hp=0;Eq(b.playerService.TryConsumeFatalDamage(),true,"구사일생 첫 치명타");Eq(p.hp,1,"구사일생 체력");Eq(p.GetBuffStack(LastStandBuffId),0,"구사일생 소모");p.hp=-20;Eq(b.playerService.TryConsumeFatalDamage(),true,"소모 후 같은 턴 치명타 방어");b.TurnSequence++;p.hp=0;Eq(b.playerService.TryConsumeFatalDamage(),false,"다음 턴 보호 종료");
  b=new();p=b.playerData;p.AddBuff(StrengthContractBuffId,3);p.AddBuff(GlacierBondBuffId,2);b.playerService.OnPlayerTurnStart();Eq(p.GetBuffStack(StrengthBuffId),0,"결속 부족 시 힘 없음");Eq(p.GetBuffStack(GlacierBondBuffId),2,"결속 부족 시 미소모");p.AddBuff(GlacierBondBuffId,1);b.playerService.OnPlayerTurnStart();Eq(p.GetBuffStack(StrengthBuffId),3,"결속 충분 시 힘");Eq(p.GetBuffStack(GlacierBondBuffId),0,"결속 충분 시 소모");
  b=new();p=b.playerData;p.mode=WuppiModeState.Attack;Eq(b.playerService.GetOutgoingDamageMultiplier(),2f,"우피 주는 피해");Eq(b.playerService.GetIncomingDamageMultiplier(null),2f,"우피 받는 피해 두 배");
  b=new();p=b.playerData;p.AddBuff(DrawLockBuffId,1);Eq(b.playerService.CanDrawCards(),false,"드로우 금지");Eq(b.playerService.CanGainCardsToHand(),true,"카드 생성 허용");Eq(b.playerService.CanGainCardsToHandFrom(MoveZoneType.DiscardPile),true,"회수 허용");b.playerService.OnPlayerTurnEnd();Eq(b.playerService.CanDrawCards(),true,"턴 종료 해제");
  p.AddBuff(PotionCycleBuffId,1);var potion=new Card{cardId=101080};b.playerService.OnCardPlayed(potion,null,false);Eq(b.draws,1,"포션 드로우");Eq(b.playerService.ShouldPotionGoToDiscardInsteadOfExhaust(potion),false,"포션 소멸 유지");
  b=new();p=b.playerData;p.AddBuff(OverheatBuffId,5);Eq(b.playerService.GetOutgoingDamageMultiplier(),1.5f,"과열 모든 피해");p.AddBuff(WeakBuffId,1);Eq(b.playerService.GetOutgoingDamageMultiplier(),1.5f,"약화 비공격 제외");Eq(b.playerService.GetCalculatedCardBaseMultiplier(1),0.75f,"약화 공격 적용");
  b=new();p=b.playerData;p.AddBuff(RegenerationBuffId,3);p.AddBuff(DoubleActionBuffId,2);b.playerService.PreparePlayerTurnEnd();Eq(b.repeats,2,"이중 동작 예약");for(int i=0;i<=b.repeats;i++)b.playerService.ReplayTurnEndTriggeredEffects();Eq(p.hp,59,"재생 세 번 발동");b.playerService.OnPlayerTurnEnd();Eq(p.GetBuffStack(RegenerationBuffId),2,"지속 시간 한 번 감소");
  b=new();p=b.playerData;p.AddBuff(DrowningOnDebuffBuffId,2);p.AddBuff(RisingWaterBuffId,3);p.AddBuff(UnderwaterBreathingBuffId,4);var m=new Monster();b.monsters.Add(m);b.ApplyBuffToMonster(m,WeakBuffId,1);Eq(m.GetBuffStack(DrowningBuffId),5,"파생 익사에 수면 상승 적용");Eq(p.defense,4,"파생 익사에 수중 호흡 적용");
  b=new();p=b.playerData;m=new Monster();b.monsters.Add(m);m.AddBuff(StrengthBuffId,5);m.AddBuff(4006,3);Eq(b.monsterService.ModifyOutgoingDamage(m,10),15,"근육 이완 즉시 감산 없음");b.monsterService.OnMonsterTurnEnd(m);Eq(m.GetBuffStack(StrengthBuffId),2,"턴 종료 힘 감소");Eq(m.GetBuffStack(4006),0,"근육 이완 소모");
  m.AddBuff(GlacierBondBuffId,4);m.AddBuff(FrailBuffId,2);Eq(b.monsterService.ResolveBarrierGain(m,10),7,"결속 후 빈약 적용");b.monsterService.OnMonsterTurnEnd(m);Eq(m.GetBuffStack(FrailBuffId),1,"몬스터 빈약 감소");
  var mirror=new MirrorMonster();b.monsters.Add(mirror);b.monsterService.OnMonsterHpLost(mirror,12);Eq(mirror.GetBuffStack(MirrorBuffId),12,"거울 최초 피해 누적");Eq(b.monsterService.ModifyOutgoingDamage(mirror,0),12,"거울 기본 공격 0 보정");b.monsterService.OnMonsterAttackResolved(mirror,p,12,0);Eq(mirror.GetBuffStack(MirrorBuffId),0,"거울 공격 후 초기화");b.monsterService.OnMonsterHpLost(mirror,7);Eq(mirror.GetBuffStack(MirrorBuffId),7,"거울 재누적");
  m.AddBuff(LifeLinkBuffId,1);int hp=p.hp;b.monsterService.OnPlayerHpLost(8);Eq(p.hp,hp,"생명 연결 반대 방향 없음");b.monsterService.OnMonsterHpLost(m,8);Eq(p.hp,hp+8,"몬스터 체력 손실만큼 플레이어 회복");b.monsterService.OnPlayerTurnEnd();Eq(m.GetBuffStack(LifeLinkBuffId),0,"생명 연결 턴 종료");
  m.AddBuff(ThornBuffId,3);hp=p.hp;b.monsterService.OnMonsterAfterTakeDamage(m,10,10);Eq(p.hp,hp,"비공격 가시 반격 없음");b.monsterService.OnAttackedByPlayer(m);Eq(p.hp,hp-3,"공격 가시 반격");
  m.AddBuff(MonsterLifeStealBuffId,5);b.monsterService.OnMonsterAttackResolved(m,p,10,10);Eq(BuffCombatUtility.stolen,1,"체력 강탈 고정 1");
  b=new();p=b.playerData;p.AddBuff(NextCardFreeBuffId,1);Eq(b.TryPayCardCost(new Card{cost=3}),true,"예고 비용 지불 성공");Eq(p.energy,3,"예고 에너지 미소모");Eq(p.GetBuffStack(NextCardFreeBuffId),0,"예고 효과 실행 전 소모");p.AddBuff(NextCardFreeBuffId,1);b.playerService.OnCardPlayed(new Card(),null,false);Eq(p.GetBuffStack(NextCardFreeBuffId),1,"사용한 카드로 얻은 예고 유지");
  b=new();p=b.playerData;p.AddBuff(LastStandBuffId,1);b.SetState(BattleTurnState.EnemyTurnStart);p.hp=0;Eq(b.playerService.TryConsumeFatalDamage(),false,"적 턴 시작에는 구사일생 미발동");b.SetState(BattleTurnState.EnemyAction);Eq(b.playerService.TryConsumeFatalDamage(),false,"적 공격에는 구사일생 미발동");Eq(p.GetBuffStack(LastStandBuffId),1,"적 턴에는 미발동 버프 유지");b.SetState(BattleTurnState.PlayerTurnStart);Eq(b.playerService.TryConsumeFatalDamage(),true,"자신의 턴 시작에는 보호 발동");b.playerService.OnPlayerTurnStart();p.hp=0;Eq(b.playerService.TryConsumeFatalDamage(),true,"시작 효과 처리 후에도 보호 유지");b.SetState(BattleTurnState.PlayerAction);p.hp=0;Eq(b.playerService.TryConsumeFatalDamage(),true,"자신의 턴 동안 보호 유지");b.SetState(BattleTurnState.PlayerTurnEnd);p.hp=0;Eq(b.playerService.TryConsumeFatalDamage(),false,"턴 종료 진입 후 보호 종료");b.SetState(BattleTurnState.EnemyAction);p.hp=0;Eq(b.playerService.TryConsumeFatalDamage(),false,"발동 후 몬스터 턴에는 보호 없음");
  b=new();p=b.playerData;p.AddBuff(ComboBuffId,1);p.AddBuff(AttackBoostBuffId,3);m=new Monster();b.monsters.Add(m);var m2=new Monster();b.monsters.Add(m2);
  for(int i=0;i<6;i++)b.HandlePlayerDamageDealt(m,1);new AttackEffect{amount=10,target=TargetType.AllEnemies}.Execute(b);
  Eq(m.hp,74,"광역 일곱 번째 타격 두 배와 강공");Eq(m2.hp,87,"광역 여덟 번째 타격 정상과 강공");Eq(p.GetBuffStack(AttackBoostBuffId),0,"강공 한 번 소모");
  b=new();p=b.playerData;p.AddBuff(StrengthBuffId,10);p.AddBuff(WeakBuffId,1);p.AddBuff(OverheatBuffId,10);m=new Monster();b.monsters.Add(m);new DamageEffect{amount=10,target=TargetType.SingleEnemy}.Execute(b);Eq(m.hp,80,"비공격 피해는 과열만 적용");
  b=new();p=b.playerData;p.AddBuff(FeatherCycleBuffId,1);b.playerService.OnFeatherApplied(2,1,TargetType.SingleEnemy);Eq(b.draws,0,"깃털 부여만으로 순환 미발동");b.playerService.OnCardPlayed(new Card{cardId=203081},null,false);Eq(b.draws,1,"깃털 카드 사용 시 순환");
  b=new();p=b.playerData;p.AddBuff(DeadlyAmbushBuffId,5);var feather=new FeatherBuffScript(b,b.playerService);m=new Monster();b.monsters.Add(m);Eq(feather.TriggerOnMonster(m),0,"깃털 없는 대상 발동 실패");m.AddBuff(FeatherBuffId,2);Eq(feather.TriggerOnMonster(m),7,"실제 첫 깃털 기습 보너스 보존");Eq(feather.TriggerOnMonster(m),1,"두 번째 깃털 추가 피해 없음");
  b=new();p=b.playerData;p.AddBuff(RegenerationBuffId,3);p.AddBuff(DoubleActionBuffId,2);b.playerService.PreparePlayerTurnEnd();b.playerService.ReplayTurnEndTriggeredEffects();new TurnSystem(b,b.repeats).FinishHand();b.playerService.OnPlayerTurnEnd();Eq(p.hp,59,"실제 빈 손패 종료 경로의 재생 반복");Eq(p.GetBuffStack(RegenerationBuffId),2,"반복 후 지속 시간 한 번 감소");
  b=new();p=b.playerData;p.AddBuff(DrowningOnDebuffBuffId,2);m=new Monster();b.monsters.Add(m);b.ApplyBuffToMonster(m,DrowningBuffId,1);Eq(m.GetBuffStack(DrowningBuffId),3,"익사 자체도 부정한 물을 한 번만 발동");
  b=new();p=b.playerData;p.AddBuff(GlacierBondBuffId,4);Eq(p.AddDefense(10),10,"결속은 버프 보호막에 미적용");Eq(p.AddDefense(10,true),14,"결속은 카드 보호막에 적용");p.AddBuff(FrailBuffId,1);Eq(p.AddDefense(10,true),7,"카드 결속 후 빈약 배율");Eq(p.AddDefense(10),5,"버프 보호막에는 빈약만 적용");
  b=new();p=b.playerData;b.SetState(BattleTurnState.EnemyAction);p.AddBuff(LifeLinkBuffId,1);m=new Monster{hp=20};m2=new Monster{hp=20};b.monsters.Add(m);b.monsters.Add(m2);p.defense=5;p.TakeDamage(12,m);Eq(p.hp,43,"생명 연결 체력 손실");Eq(m.hp,27,"공격자만 막히지 않은 피해만큼 회복");Eq(m2.hp,20,"다른 몬스터 회복 없음");p.defense=20;p.TakeDamage(10,m);Eq(m.hp,27,"보호막에 막힌 공격은 회복 없음");p.TakeDamage(20);Eq(m.hp,27,"공격자 없는 피해는 회복 없음");p.LoseHp(5);Eq(m.hp,27,"직접 체력 감소는 몬스터 회복 없음");b.playerService.OnEnemyTurnEnd();Eq(p.GetBuffStack(LifeLinkBuffId),0,"플레이어 생명 연결 적 턴 종료 해제");
  p.hp=3;p.defense=0;p.AddBuff(LifeLinkBuffId,1);p.TakeDamage(50,m);Eq(m.hp,30,"초과 피해는 생명 연결 회복량에 미포함");
  b=new();p=b.playerData;m=new Monster{hp=20};p.hp=5;p.AddBuff(LastStandBuffId,1);p.AddBuff(LifeLinkBuffId,1);b.SetState(BattleTurnState.PlayerAction);p.TakeDamage(10,m);Eq(p.hp,1,"자신의 턴 실제 치명타 보호");Eq(m.hp,24,"구사일생으로 실제 잃은 체력만 회복");p.TakeDamage(10,m);Eq(p.hp,1,"자신의 턴 반복 치명타 보호");Eq(m.hp,24,"보호 중 체력을 잃지 않으면 회복 없음");b.SetState(BattleTurnState.EnemyAction);p.TakeDamage(10,m);Eq(p.IsDead(),true,"다음 적 턴의 피해는 정상 적용");
  b=new();p=b.playerData;m=new Monster();b.monsters.Add(m);m.AddBuff(LifeLinkBuffId,1);b.monsterService.OnMonsterHpLost(m,6);Eq(p.hp,56,"몬스터 생명 연결은 플레이어 회복");b.monsterService.OnMonsterTurnEnd(m);Eq(m.GetBuffStack(LifeLinkBuffId),0,"몬스터 생명 연결 적 턴 종료 해제");
  Console.WriteLine($"버프 회귀 검증 통과: {assertions}개 단언");
 }
}
